### ISSUE TITLE
Add info from the proposal to the website

### ISSUE THREAD

**Issue by phette23** [code4lib/2024.code4lib.org#1]
https://docs.google.com/document/d/1NId8FFlZLXHzqPForbpA4CRNEXwXNsgIbeE9C1kQd-Y/edit

At a glance, there's some venue details, transportation, land acknowledgement (I don't think we've had one before? Definitely warrants a new section under venue), and safety information that might fit on the Conduct page.

**Comment by escowles** [comment]
We have included a land acknowledgement in the opening remarks — do we also want to include it in the website?

**Comment by phette23** [comment]
I think it'd be nice to have on the venues page. I will merge your PR to close this, but submit another PR for the acknowledgement, see what you think.
