### ISSUE TITLE
Remove dead links in general info

### ISSUE THREAD

**Issue by triplingual** [code4lib/2024.code4lib.org#23]
It's dead, Jim.

**Comment by triplingual** [comment]
More than one!

**Comment by phette23** [comment]
Where are these dead links? I found and fixed one but didn't see any others.

**Comment by triplingual** [comment]
Not whole pages, but sections:
http://2024.code4lib.org/general-info/scholarships#additional-funding
http://2024.code4lib.org/general-info/accessibility#parking
http://2024.code4lib.org/general-info/social/#tours

**Comment by phette23** [comment]
I see, I wasn't looking in the navigation menu. I removed all those ones by commenting out the subnav entries in the frontmatter. Do you think that was all and this can be closed?

**Comment by phette23** [comment]
Going to close as I think we got them all.
