### ISSUE TITLE
Inaccurate time(s?) on schedule

### ISSUE THREAD

**Issue by thatandromeda** [code4lib/2024.code4lib.org#43]
I see that my talk is slated for 2:25AM: https://2024.code4lib.org/talks/everything-could-have-been-different-why-computers-are-like-that

While I appreciate the can't-stop-won't-stop, 24/7 code4lib enthusiasm, I trust this is a bug.

(I think this is a more general problem, because Chad's talk precedes mine at 2:05AM: https://2024.code4lib.org/talks/everything-old-is-new-again-what-we-could-have-learned-from-a-book-on-cobol-from-1976-but-didn-t )

**Comment by escowles** [comment]
@thatandromeda yes, looks like we have PM dates that probably need to be converted to 24-hour dates to be correctly interpreted as PM instead of AM.

**Comment by escowles** [comment]
Fixed in https://github.com/code4lib/2024.code4lib.org/commit/f5c66dc5f85362d6df5e659c98dddcc410e399cd
