### ISSUE TITLE
UMich color scheme

### ISSUE THREAD

**Issue by phette23** [code4lib/2024.code4lib.org#5]
I think we can assume using the UMich color scheme is preferable to sticking with the same colors as 2023. Thankfully they have a brand site: https://brand.umich.edu/design-resources/colors/

**Comment by triplingual** [comment]
Per a Slack thread https://code4lib.slack.com/archives/C1AJTFDMF/p1694795706440419?thread_ts=1694463078.353019&cid=C1AJTFDMF, LPC would like us to use https://design-system.lib.umich.edu/.

**Comment by phette23** [comment]
I'm not sure how that differs from the color scheme I used and implementing their whole style library would be a lot of work. I see I used dark blue #00274C as primary and yellow #FFCB05 as accent, both of those are second-to-last in their categories in the color table. Hopefully that's acceptable?

**Comment by phette23** [comment]
I think this is all set for now, we can always reopen later if we need to revisit the color schema.
