### ISSUE TITLE
Lighting Talk list of speakers - Tuesday, 10:20-11:05am

### ISSUE THREAD

**Issue by ranti** [code4lib/2024.code4lib.org#75]
Here are list of the LT speakers and the titles to be listed on the 2024 website

1. Jonathan Rochkind: "A local page viewer for digitized historical material”
2. Jenn Colt: "FOLIO: It's not just..."  https://osf.io/cnpve/
3. Vera Kahn:  "Progamming Protest"
4. Shinwoo Kim: "Lambda fixity process". https://osf.io/ry7vt/
5. Eric Lease Morgan: "Free GSU!" 
6. Cary Gordon: "Let find a host for 2025 Code4Lib"
7. Barbara Cormack: "Metadata Analysis in Zephir and HathiTrust" 
8. Natasha Allen: "A Brief History of Fowling"

Thanks!

ranti.

**Comment by triplingual** [comment]
Better screenshot with all the talks. The varying alignment is an artifact of the text box resizing hold the content closely. Not thrilling.

<img width="1159" alt="Screenshot 2024-05-14 at 16 39 27" src="https://github.com/code4lib/2024.code4lib.org/assets/1789625/7a8d72ab-da89-4d83-805b-ccbde170bdf3">

**Comment by ranti** [comment]
Sounds good to me! Whichever is the easiest for you. :-)

**Comment by escowles** [comment]
I went ahead and added them to the wiki (https://wiki.code4lib.org/Code4Lib2024_Lightning_Talks) — but I'm going to leave this issue open to track doing something within the website itself.
