### ISSUE TITLE
Breakout Sessions Tuesday May 14, 2:15-3:15pm

### ISSUE THREAD

**Issue by ranti** [code4lib/2024.code4lib.org#76]
Would it OK if we also list the breakout sessions on the 2024 site?

1: ArchivesSpace tech update & community chat
2: Patron and Data Privacy
3: Transcriptions (video, audio, image) using Whisper OpenAI, google AI, etc.
4: Advocacy & Retrenchment: How do we continueour work in this world?

Don't really have the leader's info, but at least folks will know the topics. 

Thank you!

ranti.

**Comment by triplingual** [comment]
Hrm. This one may be trickier to place, and also some technical challenges for me as a Jekyll novice. I'll look, though.

**Comment by escowles** [comment]
In the past, I think these have been in the wiki instead of the website — would that be OK if it's not easy to fit them in to the website?

**Comment by ranti** [comment]
As long as people can get to it, I don't have a problem linking them to the wiki.

**Comment by escowles** [comment]
OK, I've added them to the wiki (https://wiki.code4lib.org/Code4Lib2024_Breakout_Sessions) and linked from the schedule.
