### ISSUE TITLE
Lightning Talk -  Wednesday , 10:15AM to 11:15AM

### ISSUE THREAD

**Issue by ranti** [code4lib/2024.code4lib.org#77]
Lightning Talk 1 (10:15AM to 11:15AM)
1. Micah Walter: "Smith Inventory System: How it works and lessons learned" https://osf.io/fepqc/
2. Marcabee Levine: "Bound-with Titles in  FOLIO and VuFind" - https://docs.google.com/presentation/d/1dxnGKLbSbM05JptxTm-1nKz_6UVqM9EE4rZmGwLogAA/edit?usp=sharing 
3. Eric Hellman: Browser Extension Rant
4. Michael Klein: “Things my grandfather told me [30 years later, with the help of AI audio transcription]”
5. Dee Dee Crema: ETDs@Harvard - https://osf.io/m83t5/ 
6. Patrick Galligan: On Not choosing Kubernetes OR it's OK to fail - https://osf.io/h4ud3/
7. Angela Zoss: Three(ish) Tips for Better Data Visualization - bit.ly/3vistips / https://osf.io/tqhye
8. Steve Bischof: Learning from Poggio Civitate: Data Verification
9. Thomas Dowling: Open Access Theses and Dissertations - https://oatd.org

**Comment by escowles** [comment]
Added to the wiki and linked from the schedule: https://wiki.code4lib.org/Code4Lib2024_Lightning_Talks
